### ISSUE TITLE
Add conditions in status of volume replication

### ISSUE THREAD

**Issue by iamniting** [csi-addons/volume-replication-operator#48]
As of now, we have only the State field in the status of volume replication. Which does not give us much clarity on what is the current state. Adding conditions in status will give a clear picture of the volume replication state.

**Comment by iamniting** [comment]
We can do something like this. We will mark the Spec.ReplicaState condition True when we met the state and others as false.

```yaml
status:
  conditions:
    - lastTransitionTime: "2019-10-22T16:29:24Z"
      status: "True"
      type: IsPrimary
    - lastTransitionTime: "2019-10-22T16:29:24Z"
      status: "False"
      type: IsSecondary
    - lastTransitionTime: "2019-10-22T16:29:31Z"
      status: "False"
      type: IsResyncing
```
